# answers.txt defaults
install_mariadb: y
install_glance: y
install_nova: y
install_cinder: y
install_swift: n
install_ceilometer: n
install_heat: n
ntp_servers: 0.rhel.pool.ntp.org
config_debug: y

# keystone
keystone_token_type: UUID

# neutron
neutron_ext_bridge: br-ex
neutron_ovs_bridge_mappings: "physnet1:br-ex"
neutron_ovs_bridge_ifaces: "br-ex:{{ primary_if }}"
neutron_ml2_type_drivers: vxlan, flat
neutron_dest_phys_iface: "/etc/sysconfig/network-scripts/ifcfg-{{ primary_if }}"
neutron_dest_ext_iface: /etc/sysconfig/network-scripts/ifcfg-{{ neutron_ext_bridge }}

# demo
config_demo: n
