# vim:ft=ansible
---
- name: run yum update
  yum: name=* state=latest
  tags: yum

- name: install rdo-release repo
  yum: name=https://rdoproject.org/repos/rdo-release.rpm state=present 
  tags: yum

- name: install needed packages
  yum: name={{ item }} state=latest
  with_items:
    - epel-release
    - python-pip
    - git
    - openstack-packstack
  tags:
    - yum

- name: stopping NetworkManager and starting network.service
  service: name=NetworkManager state=stopped
  tags: nm

- name: disable NetworkManager
  service: name=NetworkManager enabled=no
  tags: nm

- name: start network.service
  service: name=network.service state=started
  tags: nm

- name: enable network.service
  service: name=network.service enabled=yes
  tags: nm

- name: install packstack allinone
  command: packstack --debug --allinone --provision-demo=n
  tags: packstack
